name: Deploy on Google Cloud

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".eslintrc.cjs"
      - ".gitignore"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ vars.PNPM_VERSION }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Authenticate on Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Upload build to bucket
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: "dist"
          destination: ${{ vars.BUCKET_NAME }}
          parent: false
